server.port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:Katlegow/microservices-java-config.git
          searchPaths: [licensingservice]
          timeout: 50000
          ignore-local-ssh-settings: true
          private-key: |
                        -----BEGIN EC PRIVATE KEY-----
                       ***********************************
                        -----END EC PRIVATE KEY-----
          host-key-algorithm: ecdsa-sha2-nistp256
          host-key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
          default-label: master